# Production setup
version: '3'
services:
  api:
    image: shiroyuki/keymaster
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      KEYMASTER_SERVER_ENIGMA_KEY: ${KEYMASTER_SERVER_ENIGMA_KEY}
      KEYMASTER_JWT_SECRET: ${KEYMASTER_JWT_SECRET}
      KEYMASTER_JWT_ISSUER: ${KEYMASTER_JWT_ISSUER}
      KEYMASTER_JWT_AUDIENCE: ${KEYMASTER_JWT_AUDIENCE}
      KEYMASTER_DB_URL: mysql+pymysql://root:${RDS_SERVER_PASSWORD}@rds:3306
      KEYMASTER_DB_NAME: ${KEYMASTER_DB_NAME}

  rds:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${RDS_SERVER_PASSWORD}
    privileged: true
    volumes:
      - ./mnt/data/mysql:/var/lib/mysql
