version: '3'
services:
    api:
        image: shiroyuki/keymaster
        container_name: shiroyuki.keymaster.api
        ports:
          - 8000:8000
        volumes:
          - .:/opt/app
        environment:
          DB_URL: mysql+pymysql://root:pythonisallaround@rds:3306
          DB_NAME: keymaster

    cli:
        image: shiroyuki/keymaster
        container_name: shiroyuki.keymaster.cli
        entrypoint: bash
        command: tail -f /dev/null
        volumes:
          - .:/opt/app

    rds:
        image: mariadb:10
        container_name: shiroyuki.keymaster.rds
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: pythonisallaround
        privileged: true
        volumes:
            - ./mnt/data/mysql:/var/lib/mysql

#    redis:
#        image: redis:5-alpine
#        container_name: shiroyuki.keymaster.redis