# Production setup
version: '3'
services:
  api:
    image: shiroyuki/keymaster
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      DB_URL: mysql+pymysql://root:pythonisallaround@rds:3306
      DB_NAME: keymaster

  rds:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pythonisallaround
    privileged: true
    volumes:
      - ./mnt/data/mysql:/var/lib/mysql
