# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import keymaster_pb2 as keymaster__pb2


class KeymasterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AuthenticateUser = channel.unary_unary(
        '/Keymaster/AuthenticateUser',
        request_serializer=keymaster__pb2.UserAuthenticationRequest.SerializeToString,
        response_deserializer=keymaster__pb2.UserAuthenticationResponse.FromString,
        )
    self.Search = channel.unary_unary(
        '/Keymaster/Search',
        request_serializer=keymaster__pb2.QueryRequest.SerializeToString,
        response_deserializer=keymaster__pb2.QueriedEntries.FromString,
        )
    self.Decrypt = channel.unary_unary(
        '/Keymaster/Decrypt',
        request_serializer=keymaster__pb2.DecryptionRequest.SerializeToString,
        response_deserializer=keymaster__pb2.DecryptionResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/Keymaster/Get',
        request_serializer=keymaster__pb2.GetRequest.SerializeToString,
        response_deserializer=keymaster__pb2.GetResponse.FromString,
        )
    self.Put = channel.unary_unary(
        '/Keymaster/Put',
        request_serializer=keymaster__pb2.PutRequest.SerializeToString,
        response_deserializer=keymaster__pb2.PutResponse.FromString,
        )


class KeymasterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AuthenticateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Decrypt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeymasterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AuthenticateUser': grpc.unary_unary_rpc_method_handler(
          servicer.AuthenticateUser,
          request_deserializer=keymaster__pb2.UserAuthenticationRequest.FromString,
          response_serializer=keymaster__pb2.UserAuthenticationResponse.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=keymaster__pb2.QueryRequest.FromString,
          response_serializer=keymaster__pb2.QueriedEntries.SerializeToString,
      ),
      'Decrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Decrypt,
          request_deserializer=keymaster__pb2.DecryptionRequest.FromString,
          response_serializer=keymaster__pb2.DecryptionResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=keymaster__pb2.GetRequest.FromString,
          response_serializer=keymaster__pb2.GetResponse.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=keymaster__pb2.PutRequest.FromString,
          response_serializer=keymaster__pb2.PutResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Keymaster', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
