# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from keymaster.common.proto import keymaster_pb2 as keymaster_dot_common_dot_proto_dot_keymaster__pb2


class KeymasterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AuthenticateUser = channel.unary_unary(
        '/Keymaster/AuthenticateUser',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthenticationRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthenticationResponse.FromString,
        )
    self.AuthorizeUser = channel.unary_unary(
        '/Keymaster/AuthorizeUser',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthorizationRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthorizationResponse.FromString,
        )
    self.GetMyProfile = channel.unary_unary(
        '/Keymaster/GetMyProfile',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.BlankRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserProfileResponse.FromString,
        )
    self.GetAll = channel.unary_unary(
        '/Keymaster/GetAll',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.BlankRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.QueriedEntries.FromString,
        )
    self.Search = channel.unary_unary(
        '/Keymaster/Search',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.QueryRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.QueriedEntries.FromString,
        )
    self.Decrypt = channel.unary_unary(
        '/Keymaster/Decrypt',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.DecryptionRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.DecryptionResponse.FromString,
        )
    self.Create = channel.unary_unary(
        '/Keymaster/Create',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.NewRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.GetResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/Keymaster/Get',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.GetRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.GetResponse.FromString,
        )
    self.Put = channel.unary_unary(
        '/Keymaster/Put',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.PutRequest.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.PutResponse.FromString,
        )
    self.Sync = channel.stream_stream(
        '/Keymaster/Sync',
        request_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.SyncEntry.SerializeToString,
        response_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.SyncEntry.FromString,
        )


class KeymasterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AuthenticateUser(self, request, context):
    """Authentication and authorization
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthorizeUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyProfile(self, request, context):
    """Admin-level APIs
    User-level APIs
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Decrypt(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sync(self, request_iterator, context):
    """In Python, stream is translated into an iterator of that class.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeymasterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AuthenticateUser': grpc.unary_unary_rpc_method_handler(
          servicer.AuthenticateUser,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthenticationRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthenticationResponse.SerializeToString,
      ),
      'AuthorizeUser': grpc.unary_unary_rpc_method_handler(
          servicer.AuthorizeUser,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthorizationRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserAuthorizationResponse.SerializeToString,
      ),
      'GetMyProfile': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyProfile,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.BlankRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.UserProfileResponse.SerializeToString,
      ),
      'GetAll': grpc.unary_unary_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.BlankRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.QueriedEntries.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.QueryRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.QueriedEntries.SerializeToString,
      ),
      'Decrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Decrypt,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.DecryptionRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.DecryptionResponse.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.NewRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.GetResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.GetRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.GetResponse.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.PutRequest.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.PutResponse.SerializeToString,
      ),
      'Sync': grpc.stream_stream_rpc_method_handler(
          servicer.Sync,
          request_deserializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.SyncEntry.FromString,
          response_serializer=keymaster_dot_common_dot_proto_dot_keymaster__pb2.SyncEntry.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Keymaster', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
